language: python

notifications:
  email: false

matrix:
  include:
    - name: "Python 3.7 on Bionic Linux"
      python: 3.7
      dist: bionic
      before_install:
        - sudo apt update
        - sudo apt install graphviz
        - CURRENT_OS="Linux"
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - CURRENT_OS="MacOSX"

#     - name: "Python 3.7.3 on Windows"
#       os: windows           # Windows 10.0.17134 N/A Build 17134
#       language: shell       # 'language: python' is an error on Travis CI Windows
#       before_install:
#         - choco install python
#         - python -m pip install --upgrade pip
#       env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
    # Download miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$CURRENT_OS-x86_64.sh -O miniconda.sh

    # Install miniconda
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
   
    # Setup conda
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda

    # Install dependencies
    - conda env create -f binder/environment.yml

    # Activate environment
    - source activate tutorial

    # Post build ccmmands
    - bash binder/postBuild

    # Install testing dependencies
    # - for nb in 06*/*ipynb; do

script:
    - set -e
    - source activate tutorial
    - for nb in 06*/*ipynb; do
      if [[ $nb = *"jobqueue"* ]]; then
        echo "skipping dask jobqueue notebook $nb";
      else
        jupyter nbconvert --execute "$nb" --to markdown || exit 1;
      fi;
      done
