language: python

matrix:
  include:
    - name: "Python 3.7.3 on Bionic Linux"
      python: 3.7.3           # this works for Linux but is ignored on macOS or Windows
      dist: bionic
      before_install:
        - sudo apt update
        - sudo apt install graphviz
#     - name: "Python 3.7.2 on macOS"
#       os: osx
#       osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
#       language: shell       # 'language: python' is an error on Travis CI macOS
#     - name: "Python 3.7.3 on Windows"
#       os: windows           # Windows 10.0.17134 N/A Build 17134
#       language: shell       # 'language: python' is an error on Travis CI Windows
#       before_install:
#         - choco install python
#         - python -m pip install --upgrade pip
#       env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
    # Install conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda

    # Install dependencies
    - conda env create -f binder/environment.yml
    - source activate tutorial

    # Install testing dependencies
    - conda install pathlib nbconvert nbformat jupyter_client ipykernel

    # Install documentation dependencies
    - pip install nbsphinx dask-sphinx-theme

script:
    - set -e
    - source activate tutorial

notifications:
  email: false
