name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - bokeh=1.1.0
  - bottleneck
  - bqplot
  - cookiecutter
  - dask=2.0.0
  - dask-image=0.2.0
  - dask-jobqueue    
  - h5py
  - ipyleaflet
  - ipympl
  - ipyvolume
  - jupyterlab>=1.0
  - matplotlib
  - nodejs=8.9
  - notebook<5.7.5
  - numba
  - numpy
  - nbserverproxy
  - openpyxl
  - pandas=0.24
  - pip
  - pyarrow==0.12.0
  - pytables
  - python-graphviz
  - pythreejs
  - requests
  - scikit-learn=0.20
  - seaborn
  - tornado=5
  - sympy
  - xarray
  - xlrd
    #  - dask-ml=1.0.0
    #  - nomkl
    #  - py-xgboost
  - pip:
    - dask-labextension>=1.0
    - mimesis
      #    - dask_xgboost
