name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - h5py
  - jupyterlab>=1.0
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - pytables
  - scipy
  - xarray
  - xlrd
  - pip:
    - dask-labextension>=1.0
