#!/bin/bash

# Install the JupyterLab dask-labextension
#jupyter labextension install dask-labextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager @jupyter-widgets/jupyterlab-sidecar \
	jupyter-threejs jupyter-leaflet jupyter-matplotlib jupyter-vuetify \
	ipyvolume ipysheet ipytree \
	dask-labextension bqplot 

